export const USUARIO_A_UNIDAD_ORGANIZACIONAL_PAGE_CONFIG = {
  texts: {
    breadcrumbHome: 'Home',
    breadcrumbDomain: 'Administración',
    breadcrumbSection: 'Asignaciones',
    breadcrumbCurrent: 'Asigna Usuario - Unidad Organizacional',
    userSearchLabel: 'Buscar Usuario',
    unitSearchLabel: 'Buscar Unidad',
    organizationFilterLabel: 'Organización',
    organizationFilterPlaceholder: 'Seleccione organización',
    userSearchPlaceholder: 'Filtra por nombre o correo',
    unitSearchPlaceholder: 'Filtra por codigo, nombre o descripcion',
    searchIconAlt: 'Icono de búsqueda',
    clearSearchAction: 'Limpiar',
    usersTitle: 'Usuarios',
    unitsTitle: 'Unidades Organizacionales',
    clearAction: 'Limpiar',
    saveAction: 'Guardar',
    columns: {
      correoElectronico: 'CorreoElectronico',
      nombreADesplegar: 'NombreADesplegar',
      nacionalidad: 'Nacionalidad',
      codigo: 'Codigo',
      nombre: 'Nombre',
      descripcion: 'Descripcion',
      activo: 'Activo',
    },
    status: {
      active: 'Verdadero',
      inactive: 'Falso',
    },
    feedback: {
      loadUsersError: 'No fue posible cargar los usuarios.',
      loadOrganizationsError: 'No fue posible cargar las organizaciones.',
      loadUnitsError: 'No fue posible cargar las unidades organizacionales del contexto.',
      missingSelection: 'Selecciona un usuario y una unidad organizacional.',
      missingUserSelection: 'Selecciona un usuario para administrar sus unidades organizacionales.',
      assignSuccess: 'Usuario asignado a la unidad organizacional correctamente.',
      saveSuccess: 'Asignaciones guardadas correctamente.',
      assignError: 'No fue posible asignar el usuario a la unidad organizacional.',
      saveError: 'No fue posible guardar las asignaciones.',
      missingOrganizationContext: 'No existe una organización seleccionada en la sesión actual.',
      loadAssignmentsError: 'No fue posible cargar las entidades asociadas al usuario.',
    },
    confirm: {
      title: '¿Guardar asignaciones?',
      text: 'Se crearán y eliminarán las relaciones modificadas para el usuario seleccionado.',
      accept: 'Aceptar',
      cancel: 'Cancelar',
    },
    emptyUsersTitle: 'No hay usuarios disponibles.',
    emptyUnitsTitle: 'No hay unidades organizacionales disponibles.',
    footer: {
      selectedLabel: 'seleccionadas',
      totalLabel: 'total',
      rowsPerPage: 'Filas por pagina',
    },
  },
  pageSizeOptions: [10, 20, 50, 100] as const,
  defaultPageLimit: 10,
  tableHeaderHeight: 60,
  tableFooterHeight: 80,
};
