export const ASIGNA_UNIDAD_ORGANIZACIONAL_ORGANIZACION_PAGE_CONFIG = {
  texts: {
    breadcrumbHome: 'Home',
    breadcrumbDomain: 'Administración',
    breadcrumbSection: 'Asignaciones',
    breadcrumbCurrent: 'Asigna Unidad Organizacional a Organizacion',
    organizationFilterLabel: 'Organizacion',
    organizationFilterPlaceholder: 'Seleccione organizacion',
    unitSearchLabel: 'Buscar Unidad',
    unitSearchPlaceholder: 'Filtra por codigo, nombre u organizacion actual',
    searchIconAlt: 'Icono de busqueda',
    clearSearchAction: 'Limpiar',
    reloadAction: 'Recargar',
    saveAction: 'Guardar',
    columns: {
      asignada: 'Asignada',
      codigoUnidadOrganizacional: 'Codigo',
      nombreUnidadOrganizacional: 'Unidad Organizacional',
      descripcionUnidadOrganizacional: 'Descripcion',
      organizacionActual: 'Organizacion Actual',
      tieneEntidadPrincipal: 'Entidad Principal',
      activo: 'Activo',
    },
    status: {
      active: 'Verdadero',
      inactive: 'Falso',
      yes: 'Si',
      no: 'No',
    },
    feedback: {
      loadOrganizationsError: 'No fue posible cargar las organizaciones.',
      loadUnitsError: 'No fue posible cargar las unidades organizacionales.',
      missingOrganization: 'Selecciona una organizacion.',
      missingChanges: 'No existen cambios pendientes.',
      saveSuccess: 'Relaciones guardadas correctamente.',
      saveError: 'No fue posible guardar las relaciones.',
      unsupportedUnassign: 'La unidad no puede quedar sin organizacion. Para sacarla de esta organizacion debe asignarse a otra.',
    },
    confirm: {
      title: 'Confirmar reasignacion de unidades',
      accept: 'Continuar',
      cancel: 'Cancelar',
    },
    emptyUnitsTitle: 'No hay unidades organizacionales disponibles.',
    footer: {
      selectedLabel: 'asignadas',
      totalLabel: 'total',
      rowsPerPage: 'Filas por pagina',
    },
  },
  pageSizeOptions: [10, 20, 50, 100] as const,
  defaultPageLimit: 10,
  tableHeaderHeight: 60,
  tableFooterHeight: 80,
};
