export const ASIGNA_ROL_PROCESO_A_ENTIDAD_PAGE_CONFIG = {
  texts: {
    breadcrumbHome: 'Home',
    breadcrumbDomain: 'Administración',
    breadcrumbSection: 'Asignaciones',
    breadcrumbCurrent: 'Asigna Rol y Proceso a Entidad',
    organizationFilterLabel: 'Organización',
    organizationFilterPlaceholder: 'Seleccione organización',
    entitySearchLabel: 'Buscar Entidad',
    entitySearchPlaceholder: 'Filtra por usuario, correo, unidad o tipo',
    roleSearchLabel: 'Buscar Rol',
    roleSearchPlaceholder: 'Filtra por rol',
    processSearchLabel: 'Buscar Proceso',
    processSearchPlaceholder: 'Filtra por codigo o nombre',
    searchIconAlt: 'Icono de búsqueda',
    clearSearchAction: 'Limpiar',
    clearAction: 'Limpiar',
    saveAction: 'Guardar',
    rolesTitle: 'Roles',
    processesTitle: 'Procesos',
    currentPoliciesTitle: 'Políticas asignadas',
    columns: {
      nombreUsuario: 'Usuario',
      correoElectronico: 'Correo',
      unidadOrganizacional: 'Unidad',
      tipoDeEntidad: 'Tipo',
      principal: 'Principal',
    },
    status: {
      active: 'Verdadero',
      inactive: 'Falso',
    },
    feedback: {
      loadOrganizationsError: 'No fue posible cargar las organizaciones.',
      loadEntitiesError: 'No fue posible cargar las entidades de la organización.',
      loadCatalogsError: 'No fue posible cargar roles y procesos.',
      loadPoliciesError: 'No fue posible cargar las políticas asignadas a la entidad.',
      missingOrganizationContext: 'Debe seleccionar una organización.',
      missingEntitySelection: 'Debe seleccionar una entidad.',
      missingPolicySelection: 'Debe seleccionar al menos un rol y un proceso para la entidad.',
      missingChanges: 'No existen cambios para guardar.',
      saveSuccess: 'Políticas asignadas guardadas correctamente.',
      saveError: 'No fue posible guardar las políticas asignadas.',
      noPermission: 'El usuario autenticado no tiene permisos administrativos para esta pantalla.',
    },
    confirm: {
      title: '¿Guardar políticas asignadas?',
      text: 'Se crearán y eliminarán las relaciones modificadas para la entidad seleccionada.',
      accept: 'Aceptar',
      cancel: 'Cancelar',
    },
    emptyEntitiesTitle: 'No hay entidades disponibles para la organización seleccionada.',
    emptyRolesTitle: 'No hay roles disponibles.',
    emptyProcessesTitle: 'No hay procesos disponibles.',
    footer: {
      selectedLabel: 'seleccionadas',
      totalLabel: 'total',
      rowsPerPage: 'Filas por pagina',
    },
  },
  pageSizeOptions: [10, 20, 50, 100] as const,
  defaultPageLimit: 10,
  tableHeaderHeight: 60,
  tableFooterHeight: 80,
};
