export const VALIDA_ASIGNA_ROLES_PAGE_CONFIG = {
  texts: {
    breadcrumbHome: 'Home',
    breadcrumbDomain: 'Administracion',
    breadcrumbSection: 'Validaciones',
    breadcrumbCurrent: 'Valida Asignacion Roles',
    searchLabel: 'Buscar asignacion',
    searchPlaceholder: 'Filtra por usuario, correo, rol, proceso, organizacion o unidad',
    searchIconAlt: 'Icono de busqueda',
    clearSearchAction: 'Limpiar',
    refreshAction: 'Recargar',
    validateSelectedAction: 'Validar seleccionados',
    columns: {
      seleccionar: 'Seleccionar',
      usuario: 'Usuario',
      correo: 'Correo',
      organizacion: 'Organizacion',
      unidad: 'Unidad',
      rol: 'Rol',
      proceso: 'Proceso',
      fechaCreacion: 'Fecha creacion',
      requiereValidacion: 'Requiere validacion',
      validado: 'Validado',
    },
    status: {
      yes: 'Si',
      no: 'No',
      noData: '-',
    },
    feedback: {
      loadError: 'No fue posible cargar las asignaciones de roles pendientes de validacion.',
      noPermission: 'El usuario autenticado no tiene el rol VALIDA_ASIGNACION_ROLES.',
      missingSelection: 'Debe seleccionar al menos una asignacion pendiente.',
      missingValidatorUser: 'No fue posible determinar el usuario validador autenticado.',
      validateSuccess: 'Asignaciones de roles validadas correctamente.',
      validatePartial: 'Algunas asignaciones no pudieron ser validadas.',
      validateError: 'No fue posible validar las asignaciones seleccionadas.',
    },
    confirm: {
      title: 'Validar asignaciones seleccionadas',
      text: 'Se informara al backend cada politica asignada validada y el usuario que realiza la validacion.',
      accept: 'Validar',
      cancel: 'Cancelar',
    },
    emptyTitle: 'No hay asignaciones de roles pendientes de validacion.',
    footer: {
      selectedLabel: 'seleccionadas',
      totalLabel: 'total',
      rowsPerPage: 'Filas por pagina',
    },
  },
  pageSizeOptions: [10, 20, 50, 100] as const,
  defaultPageLimit: 10,
  tableHeaderHeight: 60,
  tableFooterHeight: 80,
};
