export const VALIDA_USUARIO_NUEVO_PAGE_CONFIG = {
  texts: {
    breadcrumbHome: 'Home',
    breadcrumbDomain: 'Administracion',
    breadcrumbSection: 'Validaciones',
    breadcrumbCurrent: 'Valida Usuario Nuevo',
    searchLabel: 'Buscar usuario',
    searchPlaceholder: 'Filtra por nombre, correo, tipo, estado o documento',
    searchIconAlt: 'Icono de busqueda',
    clearSearchAction: 'Limpiar',
    refreshAction: 'Recargar',
    validateSelectedAction: 'Validar seleccionados',
    columns: {
      seleccionar: 'Seleccionar',
      nombre: 'Usuario',
      correo: 'Correo',
      tipoDeUsuario: 'Tipo',
      documento: 'Documento',
      nacionalidad: 'Nacionalidad',
      estado: 'Estado',
      correoConfirmado: 'Correo confirmado',
      requiereValidacion: 'Requiere validacion',
    },
    status: {
      yes: 'Si',
      no: 'No',
      noData: '-',
    },
    feedback: {
      loadError: 'No fue posible cargar los usuarios pendientes de validacion.',
      noPermission: 'El usuario autenticado no tiene el rol VALIDA_ENRROLAMIENTO.',
      missingSelection: 'Debe seleccionar al menos un usuario pendiente.',
      missingValidatorUser: 'No fue posible determinar el usuario validador autenticado.',
      validateSuccess: 'Usuarios validados correctamente.',
      validatePartial: 'Algunos usuarios no pudieron ser validados.',
      validateError: 'No fue posible validar los usuarios seleccionados.',
    },
    confirm: {
      title: 'Validar usuarios seleccionados',
      text: 'Se informara al backend cada usuario validado y el usuario que realiza la validacion.',
      accept: 'Validar',
      cancel: 'Cancelar',
    },
    emptyTitle: 'No hay usuarios nuevos pendientes de validacion.',
    footer: {
      selectedLabel: 'seleccionados',
      totalLabel: 'total',
      rowsPerPage: 'Filas por pagina',
    },
  },
  pageSizeOptions: [10, 20, 50, 100] as const,
  defaultPageLimit: 10,
  tableHeaderHeight: 60,
  tableFooterHeight: 80,
};
